export { Home } from './Home'
export { Login } from './Login'
export { Registro } from './Registro'
export { Download } from './Download'
export { Comunidade } from './Comunidade'
export { Regras } from './Regras'
export { Doacoes } from './Doacoes'
export { RankingPage as Ranking } from './RankingPage'
export {ForgotPassword} from './ForgotPassword'
